main:
  # Worker threads
  workers: 4
  # Listen port
  port: 995
  # Listen address (ipv4|ipv6)
  listen-address: '::'
  # DNS server address (ipv4|ipv6)
  dns-address: 8.8.8.8
  # Resolve domain to IPv6 address first
  ipv6-first: false

#auth:
#  username:
#  password:

misc:
  # null, stdout, stderr or file-path
  log-file: stdout
  # debug, info, warn or error
  log-level: warn
  # If present, run as a daemon with this pid file
  #pid-file: /run/socks5-server.pid
  # If present, set rlimit nofile; else use default value
  #limit-nofile: -1
